name: stackfood_multivendor_restaurant
description: An application for multivendor ecommerce restaurant.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.0.6
  connectivity_plus: ^5.0.2
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^16.3.0
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  shimmer_animation: ^2.0.0
  image_picker: ^1.0.7
  http: ^1.1.2
  pin_code_fields: ^8.0.1
  url_launcher: ^6.1.2
  vibration: ^1.7.6
  audioplayers: ^5.2.1
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.0.0
  phone_numbers_parser: ^8.1.3
  country_code_picker: ^3.0.0
  flutter_widget_from_html_core: ^0.14.11
  google_maps_flutter: ^2.1.1
  geolocator: ^10.1.0
  card_swiper: ^3.0.1
  flutter_pos_printer_platform: ^1.1.0
  esc_pos_utils: ^1.1.0
  screenshot: ^2.1.0
  image: ^3.0.8
  modal_bottom_sheet: ^2.1.2
  intl: ^0.18.0
  path: ^1.8.2
  http_parser: ^4.0.2
  dotted_border: ^2.0.0+2
  carousel_slider: ^4.0.0
  photo_view: ^0.14.0
  flutter_inappwebview: ^6.0.0
  just_the_tooltip: ^0.0.12
  file_picker: ^6.0.0
  custom_info_window: ^1.0.1
  syncfusion_flutter_charts: ^24.1.45+2
  modal_progress_hud_nsn: ^0.5.1
  flutter_svg: 2.0.10+1
  google_maps_flutter_web: ^0.5.6+2
  universal_html: ^2.0.8
  pointer_interceptor: ^0.10.1
  cached_network_image: ^3.3.0
  google_sign_in: ^5.4.2
  google_sign_in_web: ^0.10.2
  flutter_facebook_auth: ^6.0.4
  share_plus: ^7.2.1
  custom_map_markers: ^0.0.2+1
  image_compression_flutter: ^1.0.2
  expandable_bottom_sheet: ^1.1.1+1
  uni_links: ^0.5.1
  sign_in_with_apple: ^5.0.0
  flutter_html: 3.0.0-alpha.5
  flutter_widget_from_html: ^0.14.11
  flutter_slidable: ^3.0.0
  animated_flip_counter: ^0.2.0
  meta_seo: ^3.0.5
  fluttertoast: ^8.2.4
  marquee: ^2.2.3
  syncfusion_flutter_datepicker: ^24.1.45
  firebase_crashlytics: ^3.4.3
  lottie: ^2.3.0
  badges: ^3.1.2
  cloud_firestore: ^4.17.5
    #  flutter_polyline_points: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3
    - assets/lottie_animation/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900