// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWQSfvE6K2GuyJEJxzb6PrvM8AAnDI3_U',
    appId: '1:683435031995:web:cda06d8a1ecfc89d39189e',
    messagingSenderId: '683435031995',
    projectId: 'foodtrackpos',
    authDomain: 'foodtrackpos.firebaseapp.com',
    storageBucket: 'foodtrackpos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc0tldUK9JK7O-BCxIsVhuOBFtFVUDHeA',
    appId: '1:683435031995:android:7942f026648fa5a339189e',
    messagingSenderId: '683435031995',
    projectId: 'foodtrackpos',
    storageBucket: 'foodtrackpos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADDTtrFzO4YFVz6lhM2Xr1afCg79PXkFs',
    appId: '1:683435031995:ios:489aeb4ae6dbb8a039189e',
    messagingSenderId: '683435031995',
    projectId: 'foodtrackpos',
    storageBucket: 'foodtrackpos.appspot.com',
    iosBundleId: 'com.sixamtech.stackFoodRestaurant',
  );
}
